# Generated by Django 4.1.7 on 2023-10-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/users/default.jpg', upload_to='images/users/'),
        ),
    ]
