# Generated by Django 4.2.5 on 2023-10-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('users', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.ForeignKey(blank=True, default='KZT', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='currencies.currency'),
        ),
    ]
